name: Call Notion Updater

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC
  workflow_dispatch:      # allow manual manual run from GitHub

jobs:
  call-vercel-function:
    runs-on: ubuntu-latest
    steps:
      - name: Call your Vercel API Route
        run: |
          curl -X GET \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
          "https://life-notion.vercel.app/api/updateDaysLeft"
